GGGG/* Main.c file generated by Pitias Tsegu
 *light traking robot
 * Created:   ??? MAY 2012
 * Processor: PIC16F84A
 * Compiler:  HI-TECH C for PIC10/12/16
 */


#include<htc.h>
__CONFIG(0x3FF1);
#define PORTBIT(adr, bit)       ((unsigned)(&adr)*8+(bit))
static bit LD1 @ PORTBIT(PORTB,2);
static bit LD2 @ PORTBIT(PORTB,3);
static bit SIGIO @ PORTBIT(PORTB,4);
#define STRIS TRISBbits.TRISB4            //Defines STRIS as TRISB pin 4
void init(void)
{     
TRISB=0b00001100;
}
unsigned int i;
void forward();
void right();
void left();
void halt();

void main(void)
{ 
init();
while(1)
{
if((LD1==1)&&(LD2==1))                 
{forward();}
else if(LD1==1)
{right();}
else if(LD2==1)
{left();}
else halt();
	__delay_ms(1000);}}

void halt()
{PORTB=0b00000000;
	__delay_ms(1000);}
	
void forward()
{PORTB=0b00000011;
__delay_ms(1000); 
}
void right()
{PORTB=0b00000001;
__delay_ms(1000);}

void left()           
{PORTB=0b00000010;
__delay_ms(1000);}
